[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build --build-arg MONGO_URL=${MONGO_URL} --build-arg JWT_SECRET=${JWT_SECRET} --build-arg JWT_EXPIRES_IN=${JWT_EXPIRES_IN} --build-arg NODE_ENV=${NODE_ENV} --build-arg PORT=${PORT} ."

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[variables]
MONGO_URL = "${MONGO_URL}"
JWT_SECRET = "${JWT_SECRET}"
JWT_EXPIRES_IN = "${JWT_EXPIRES_IN}"
NODE_ENV = "production"
PORT = "3001"
